---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-headless
spec:
  selector:
    matchLabels:
      app: api-headless
  template:
    spec:
      initContainers:
        - name: migrate-database
          imagePullPolicy: Always
      containers:
        - name: api-headless
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              value: staging
