---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-headless
spec:
  template:
    spec:
      initContainers:
        - name: migrate-database
          image: ghcr.io/podkrepi-bg/api/migrations:master
          imagePullPolicy: Always
      containers:
        - name: api-headless
          image: ghcr.io/podkrepi-bg/api:master
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              value: staging
