apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podkrepibg-dev

bases:
  - "../../base"

resources:
 - keycloak-secret.local.yaml
 - sendgrid-secret.local.yaml
 - stripe-secret.local.yaml

patches:
  - path: keycloak-config.patch.yaml
  - path: api-headless.patch.yaml

images:
  - name: ghcr.io/podkrepi-bg/api/migrations
    newTag: master
  - name: ghcr.io/podkrepi-bg/api
    newTag: master
