---
apiVersion: v1
kind: Service
metadata:
  name: api-headless
  namespace: podkrepibg
spec:
  selector:
    app: api-headless
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-headless
  namespace: podkrepibg
  labels:
    app: api-headless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-headless
  template:
    metadata:
      labels:
        app: api-headless
    spec:
      initContainers:
        - name: migrate-database
          image: ghcr.io/podkrepi-bg/api/migrations:v0.1.2
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-api
                  key: url
      containers:
        - name: api-headless
          image: ghcr.io/podkrepi-bg/api:v0.1.2
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              memory: 256Mi
              cpu: '0.2'
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: APP_ENV
              value: production
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '80'
            - name: TARGET_APP
              value: api
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-api
                  key: url
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: keycloak-headless
                  key: url
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: keycloak-headless
                  key: realm
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: keycloak-headless
                  key: client-id
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-headless
                  key: secret
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-headless
                  key: apikey
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-headless
                  key: webhookSecret
            - name: SENDGRID_SENDER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: stripe-config
                  key: sender-email
            - name: SENDGRID_INTERNAL_NOTIFICATIONS_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: stripe-config
                  key: internal-notifications-email
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: apikey
