name: Check PR

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  debug-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow actor
        run: echo "${{ toJSON(github.pull_request.user) }}"
  security-checks:
    name: Security tests
    if: |
      !github.event.pull_request.head.repo.fork && github.pull_request.user.login != 'dependabot[bot]'
    uses: ./.github/workflows/security-checks.yml
    secrets:
      MONDOO_SECRET: ${{ secrets.MONDOO_SECRET }}
