name: Check PR

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  security-checks:
    name: Security tests
    needs: [check-label]
    uses: ./.github/workflows/security-checks.yaml
    secrets:
      MONDOO_SECRET: ${{ secrets.MONDOO_SECRET }}
